# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '2'

tasks:
  default:
    cmds:
    - task --list
    silent: true

  clean:
    desc: Clean build artifacts
    cmds:
    - rm -rf node_modules/
    silent: true

  setup:
    desc: Install ncc
    cmds:
    - npm install -g @vercel/ncc
    silent: true

  prepare:
    desc: Download node modules
    cmds:
    - npm install
    silent: true

  build:
    desc: Compile Node.js module
    deps:
    - task: prepare
    cmds:
    - npm run build
    silent: true

  git:tag:
    desc: Create release tag
    preconditions:
    - sh: '{{if empty .GIT_TAG}}false{{end}}'
      msg: 'Variable "GIT_TAG" is required (e.g. task git:tag GIT_TAG=0.0.0)'
    cmds:
    - git tag --annotate --message='release v{{.GIT_TAG}}' --sign {{.GIT_TAG}}
    - git --no-pager tag -n
    silent: true

  lint:
    desc: Run all linters
    cmds:
    - task: markdownlint
    - task: yamllint
    silent: true

  markdownlint:
    desc: Lint Markdown files
    cmds:
    - docker run -it --rm --volume "$(pwd):/work" tmknom/markdownlint:latest --config .github/linters/.markdown-lint.yml --ignore node_modules/ .
    silent: true

  yamllint:
    desc: Lint YAML files
    cmds:
    - yamllint --config-file .github/linters/.yaml-lint.yml --format auto --strict .
    silent: true
