version: '2'

tasks:
  default:
    cmds:
    - task --list
    silent: true

  test:
    desc: Test action
    env:
      INPUT_CHANGELOG_FILE: './CHANGELOG.md'
      INPUT_RELEASE_NOTES_FILE: 'RELEASE_NOTES.md'
    cmds:
    - docker build --tag ffurrer/extract-release-notes-action:latest .
    - docker run -it --rm --volume "$(pwd):/workdir" --workdir /workdir --env INPUT_CHANGELOG_FILE --env INPUT_RELEASE_NOTES_FILE ffurrer/extract-release-notes-action:latest

  shellcheck:
    desc: Lint shell scripts
    cmds:
    - shellcheck --check-sourced --color=auto --format=tty --enable=all --source-path=./ --shell=bash --severity=style src/extract_release_notes.sh

  yamllint:
    desc: Lint YAML files
    cmds:
    - yamllint --format auto --strict .
