# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '2'

tasks:
  default:
    cmds:
    - task --list
    silent: true

  test:
    desc: Test action
    env:
      INPUT_CHANGELOG_FILE: './CHANGELOG.md'
      INPUT_RELEASE_NOTES_FILE: 'RELEASE_NOTES.md'
    cmds:
    - docker build --tag ffurrer/extract-release-notes-action:latest .
    - docker run -it --rm --volume "$(pwd):/workdir" --workdir /workdir --env INPUT_CHANGELOG_FILE --env INPUT_RELEASE_NOTES_FILE ffurrer/extract-release-notes-action:latest

  container-structure-test:
    desc: Run container structure tests
    cmds:
    - docker build --tag ffurrer/extract-release-notes-action:latest .
    - container-structure-test test --image ffurrer/extract-release-notes-action:latest --config test/container_structure_test.yml

  lint:
    desc: Run all linters
    cmds:
    - task: hadolint
    - task: markdownlint
    - task: shellcheck
    - task: yamllint
    silent: true

  hadolint:
    desc: Lint Dockerfiles
    cmds:
    - hadolint --format tty Dockerfile
    silent: true

  markdownlint:
    desc: Lint Markdown files
    cmds:
    - docker run -it --rm --volume "$(pwd):/work" tmknom/markdownlint:latest --config .github/linters/.markdown-lint.yml .
    silent: true

  shellcheck:
    desc: Lint shell scripts
    cmds:
    - shellcheck --check-sourced --color=auto --format=tty --enable=all --source-path=./ --shell=bash --severity=style src/extract_release_notes.sh
    silent: true

  yamllint:
    desc: Lint YAML files
    cmds:
    - yamllint --config-file .github/linters/.yaml-lint.yml --format auto --strict .
    silent: true
