# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

tasks:
  list:
    desc: List dependencies
    cmds:
    - licensed list
    silent: true

  status:
    desc: Check licensed status
    cmds:
    - licensed status
    silent: true

  cache:
    desc: Update licensed cache
    cmds:
    - npm ci
    - licensed cache --force
    silent: true

  notices:
    desc: Generate NOTICE file
    cmds:
    - licensed notices
    silent: true
