# SPDX-License-Identifier: MIT
name: CI

on:
  push:
    branches:
    - master
    - feature/**
    - dependabot/**
    paths-ignore:
    - '**.md'
    - '.gitignore'

jobs:
  self-test-1:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11.0, windows-2019 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Self test
      id: extract-release-notes
      uses: ./
    - name: Assert release_notes is not empty
      shell: bash
      env:
        RELEASE_NOTES: ${{ steps.extract-release-notes.outputs.release_notes }}
      run: |
        test -n "${RELEASE_NOTES}"

  self-test-2:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11.0, windows-2019 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Self test
      uses: ./
      with:
        release_notes_file: RELEASE_NOTES.md
    - name: Assert release-notes-file exist
      shell: bash
      run: |
        test -f RELEASE_NOTES.md

  self-test-3:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11.0, windows-2019 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Self test
      id: extract-release-notes
      uses: ./
      with:
        changelog_file: test/testdata/CHANGELOG_1.md
    - name: Assert release_notes output contains expected content
      shell: bash
      env:
        RELEASE_NOTES: ${{ steps.extract-release-notes.outputs.release_notes }}
      run: |
        expected_output=$(cat <<-EOF
        ### Added

        - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        - At vero eos et accusam et justo duo dolores et ea rebum.
        - Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
        - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        - At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

        ### Changed

        - At vero eos et accusam et justo duo dolores et ea rebum.
        - Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

        ### Removed

        - At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
        EOF
        )
        diff <(echo "${RELEASE_NOTES}") <(echo "$expected_output")

  self-test-4:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11.0, windows-2019 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Self test
      id: extract-release-notes
      uses: ./
      with:
        changelog_file: test/testdata/CHANGELOG_2.md
    - name: Assert release_notes output contains expected content
      shell: bash
      env:
        RELEASE_NOTES: ${{ steps.extract-release-notes.outputs.release_notes }}
      run: |
        readonly expected_output=$(cat <<-EOF
        ### Added

        - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        - At vero eos et accusam et justo duo dolores et ea rebum.
        - Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
        - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        - At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

        ### Changed

        - At vero eos et accusam et justo duo dolores et ea rebum.
        - Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
        EOF
        )
        diff <(echo "${RELEASE_NOTES}") <(echo "$expected_output")

  self-test-5:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Self test
      id: extract-release-notes
      uses: ./
      with:
        changelog_file: test/testdata/CHANGELOG_3.md
    - name: Assert release_notes output contains expected content
      shell: bash
      env:
        RELEASE_NOTES: ${{ steps.extract-release-notes.outputs.release_notes }}
      run: |
        readonly expected_output=$(cat <<-EOF
        ### Added

        - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        EOF
        )
        diff <(echo "${RELEASE_NOTES}") <(echo "$expected_output")

  self-test-6:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11.0, windows-2019 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Self test
      id: extract-release-notes
      uses: ./
      with:
        changelog_file: test/testdata/CHANGELOG_1.md
        release_notes_file: RELEASE_NOTES.md
    - name: Assert release-notes-file contains expected content
      shell: bash
      env:
        RELEASE_NOTES: ${{ steps.extract-release-notes.outputs.release_notes }}
      run: |
        expected_output=$(cat <<-EOF
        ### Added

        - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        - At vero eos et accusam et justo duo dolores et ea rebum.
        - Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
        - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        - At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

        ### Changed

        - At vero eos et accusam et justo duo dolores et ea rebum.
        - Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

        ### Removed

        - At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
        EOF
        )
        diff  <(cat RELEASE_NOTES.md) <(echo -n "$expected_output")
