# SPDX-License-Identifier: MIT
name: CI

on:
  push:
    branches:
    - master
    - feature/*
    paths-ignore:
    - '**.md'

jobs:
  static-analysis:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Shellcheck
      uses: docker://koalaman/shellcheck:v0.7.0
      with:
        entrypoint: /bin/shellcheck
        args: '--check-sourced --color=always --format=tty --enable=all --shell=bash --severity=style src/extract_release_notes.sh'

  test-1:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Bats tests
      uses: ./.github/actions/bats
      with:
        args: /github/workspace/test/bats

  test-2:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Self test
      id: extract_release_notes
      uses: ./
    - name: Assert release_notes is not empty
      env:
        RELEASE_NOTES: ${{ steps.extract_release_notes.outputs.release_notes }}
      run: |
        test -v RELEASE_NOTES
        test -n "$RELEASE_NOTES"

  test-3:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Self test
      uses: ./
      with:
        release_notes_file: ./RELEASE_NOTES.md
    - name: Assert release_notes_file exist
      run: |
        test -f ./RELEASE_NOTES.md

  test-4:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Self test
      id: extract_release_notes
      uses: ./
      with:
        changelog_file: test/resources/CHANGELOG_1.md
    - name: Assert release_notes output contains expected content
      env:
        RELEASE_NOTES: ${{ steps.extract_release_notes.outputs.release_notes }}
      run: |
        expected_output=$(cat <<-EOF
        ### Added

        - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        - At vero eos et accusam et justo duo dolores et ea rebum.
        - Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
        - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        - At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

        ### Changed

        - At vero eos et accusam et justo duo dolores et ea rebum.
        - Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

        ### Removed

        - At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
        EOF
        )
        diff <(echo "$RELEASE_NOTES") <(echo "$expected_output")

  test-5:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Self test
      id: extract_release_notes
      uses: ./
      with:
        changelog_file: test/resources/CHANGELOG_2.md
    - name: Assert release_notes output contains expected content
      env:
        RELEASE_NOTES: ${{ steps.extract_release_notes.outputs.release_notes }}
      run: |
        readonly expected_output=$(cat <<-EOF
        ### Added

        - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        - At vero eos et accusam et justo duo dolores et ea rebum.
        - Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
        - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        - At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

        ### Changed

        - At vero eos et accusam et justo duo dolores et ea rebum.
        - Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
        EOF
        )
        diff <(echo "$RELEASE_NOTES") <(echo "$expected_output")

  test-6:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Self test
      id: extract_release_notes
      uses: ./
      with:
        changelog_file: test/resources/CHANGELOG_3.md
    - name: Assert release_notes output contains expected content
      env:
        RELEASE_NOTES: ${{ steps.extract_release_notes.outputs.release_notes }}
      run: |
        readonly expected_output=$(cat <<-EOF
        ### Added

        - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        EOF
        )
        diff <(echo "$RELEASE_NOTES") <(echo "$expected_output")

  test-7:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Self test
      id: extract_release_notes
      uses: ./
      with:
        changelog_file: test/resources/CHANGELOG_1.md
        release_notes_file: ./RELEASE_NOTES.md
    - name: Assert release_notes_file contains expected content
      env:
        RELEASE_NOTES: ${{ steps.extract_release_notes.outputs.release_notes }}
      run: |
        expected_output=$(cat <<-EOF
        ### Added

        - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        - At vero eos et accusam et justo duo dolores et ea rebum.
        - Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
        - Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        - At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

        ### Changed

        - At vero eos et accusam et justo duo dolores et ea rebum.
        - Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

        ### Removed

        - At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
        EOF
        )
        diff  <(cat ./RELEASE_NOTES.md) <(echo -n "$expected_output")
