# SPDX-License-Identifier: MIT
name: markdownlint

on:
  push:
    branches:
    - main
    - feature/**
    - dependabot/**
    paths:
    - '**.md'
    - '.github/linters/.markdown-lint.yml'
    - '.github/workflows/markdownlint.yml'

jobs:
  markdownlint:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: markdownlint
      uses: nosborn/github-action-markdown-cli@58bcfd1af530d87a13d51b76e6713b52602e3613 # v3.4.0
      with:
        config_file: .github/linters/.markdown-lint.yml
        files: .
        ignore_files: test/testdata/expected
