# SPDX-License-Identifier: MIT
name: Move major tag

on:
  release:
    types:
    - published
    - edited

jobs:
  actions-tagger:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - uses: Actions-R-Us/actions-tagger@v2
      with:
        token: ${{secrets.GITHUB_TOKEN}}
