# SPDX-License-Identifier: MIT
name: Move major tag

on:
  release:
    types:
    - published

jobs:
  actions-tagger:
    runs-on: ubuntu-18.04
    steps:
    - uses: Actions-R-Us/actions-tagger@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
